//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcftest_in_charp.wcftest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/wcftest", ConfigurationName="wcftest.wcftest_Port")]
    public interface wcftest_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Ping_Result) of message Ping_Result does not match the default value (Ping)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/wcftest:Ping", ReplyAction="*")]
        wcftest_in_charp.wcftest.Ping_Result Ping(wcftest_in_charp.wcftest.Ping request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/wcftest:Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<wcftest_in_charp.wcftest.Ping_Result> PingAsync(wcftest_in_charp.wcftest.Ping request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/wcftest", IsWrapped=true)]
    public partial class Ping {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/wcftest", Order=0)]
        public string parm;
        
        public Ping() {
        }
        
        public Ping(string parm) {
            this.parm = parm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/wcftest", IsWrapped=true)]
    public partial class Ping_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/wcftest", Order=0)]
        public string return_value;
        
        public Ping_Result() {
        }
        
        public Ping_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wcftest_PortChannel : wcftest_in_charp.wcftest.wcftest_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wcftest_PortClient : System.ServiceModel.ClientBase<wcftest_in_charp.wcftest.wcftest_Port>, wcftest_in_charp.wcftest.wcftest_Port {
        
        public wcftest_PortClient() {
        }
        
        public wcftest_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wcftest_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcftest_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcftest_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wcftest_in_charp.wcftest.Ping_Result wcftest_in_charp.wcftest.wcftest_Port.Ping(wcftest_in_charp.wcftest.Ping request) {
            return base.Channel.Ping(request);
        }
        
        public string Ping(string parm) {
            wcftest_in_charp.wcftest.Ping inValue = new wcftest_in_charp.wcftest.Ping();
            inValue.parm = parm;
            wcftest_in_charp.wcftest.Ping_Result retVal = ((wcftest_in_charp.wcftest.wcftest_Port)(this)).Ping(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wcftest_in_charp.wcftest.Ping_Result> wcftest_in_charp.wcftest.wcftest_Port.PingAsync(wcftest_in_charp.wcftest.Ping request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<wcftest_in_charp.wcftest.Ping_Result> PingAsync(string parm) {
            wcftest_in_charp.wcftest.Ping inValue = new wcftest_in_charp.wcftest.Ping();
            inValue.parm = parm;
            return ((wcftest_in_charp.wcftest.wcftest_Port)(this)).PingAsync(inValue);
        }
    }
}
